### PR TITLE
chore: update badges

### PR DESCRIPTION
**Pull request by divine**
These badges might be relevant, you can discard them if you don't like them.

Thanks!

### CODE REVIEW

**Comment by msimerson** [comment]
Since you've already done this, care to also remove the TODO section in the README, and the two badges within it? Thanks again.

**Comment by divine** [comment]
Should I bump the version in package.json and update Changes.md as well?

Thank you!

**Comment by msimerson** [comment]
Go ahead and update Changes. package.json was already bumped very recently. 😉

**Comment by divine** [comment]
Glad to help!

Thank you so much for the fast review and for the software as well, I'll be looking into other projects of Haraka (ready to help), quite happy with it 👍.

**Comment by divine** [comment]
Looks like `npm publish` is required 😄

**Comment by msimerson** [comment]
````
 ✗ npm publish
npm notice 
npm notice 📦  haraka-plugin-limit@1.0.5
npm notice === Tarball Contents === 
npm notice 137B   .codeclimate.yml               
npm notice 279B   .eslintrc.yaml                 
npm notice 462B   .github/dependabot.yml         
npm notice 691B   .github/workflows/ci-test.yml  
npm notice 618B   .github/workflows/coveralls.yml
npm notice 399B   .github/workflows/lint.yml     
npm notice 533B   Changes.md                     
npm notice 1.1kB  LICENSE                        
npm notice 7.7kB  README.md                      
npm notice 2.0kB  config/limit.ini               
npm notice 20.0kB index.js                       
npm notice 1.1kB  package.json                   
npm notice 1.5kB  test/config.js                 
npm notice 1.9kB  test/config/limit.ini          
npm notice 1.5kB  test/history.js                
npm notice 815B   test/inheritance.js            
npm notice 4.2kB  test/limit.js                  
npm notice 1.4kB  test/outbound.js               
npm notice 5.7kB  test/rate_limit.js             
npm notice === Tarball Details === 
npm notice name:          haraka-plugin-limit                     
npm notice version:       1.0.5                                   
npm notice filename:      haraka-plugin-limit-1.0.5.tgz           
npm notice package size:  12.0 kB                                 
npm notice unpacked size: 52.0 kB                                 
npm notice shasum:        43c1da43bfd45c03cc7493eb1df8c9a5becf88d7
npm notice integrity:     sha512-RdG3Vme7zxGOp[...]sj+4UwdyxcVtA==
npm notice total files:   19                                      
npm notice 
This operation requires a one-time password.
Enter OTP: 232560
+ haraka-plugin-limit@1.0.5
````

hmmm, someone should also add .github to .npmignore

**Comment by divine** [comment]
Will do it now, no problem :)

**Comment by divine** [comment]
Looks like if I push .npmignore then .gitignore will be ignored completely. That means it should be done globally on the local PC.

**Comment by msimerson** [comment]
> Looks like if I push .npmignore then .gitignore will be ignored completely. That means it should be done globally on the local PC.

true, but with Haraka project, we have multiple people that can release. The workaround is to copy .gitignore to .npmignore and make the change.

**Pull request merged**
